### ISSUE TITLE
Check Github File Downloading 

### ISSUE THREAD

**Issue by xXxTheDarkprogramerxXx** [xXxTheDarkprogramerxXx/PS3Tools#50]
SLUS-20179 | THE X-FILES - RESIST OR SERVE NTSC

_Originally posted by @curtisday in https://github.com/xXxTheDarkprogramerxXx/PS3Tools/issues/30#issuecomment-583567668_

**Comment by xXxTheDarkprogramerxXx** [comment]
Found the bug with regards to app not handling download content from Github.

I am doing a fix now to see if this resolves your problem should be in the next release

**Comment by xXxTheDarkprogramerxXx** [comment]
Issue has been fixed 
Will be in next release

**Comment by ghost** [comment]
Thanks!!!

**Comment by ghost** [comment]
Hey man! I just built a pkg for X-Files and this is still not working on version 26.

**Comment by xXxTheDarkprogramerxXx** [comment]
I don't think i ever published the latest release 

Sorry about that as soon as i get a chance over the next few weeks ill publish it 

Busy setting up a remote work environment at the office because of recent events

**Comment by ghost** [comment]
ok no sweat! Stay safe, brother!

**Comment by xXxTheDarkprogramerxXx** [comment]
Should be fixed in latest release if not please reopen this issue
